name: Kaggles
channels:
  - defaults
dependencies:
  - python=3.8
  - pip
  - cudatoolkit=10.2
  - scipy
  - pytorch=1.12
  - shapely
  - ipykernel
  - matplotlib
  - seaborn
  - scikit-learn
  - pip:
    - 'mujoco-py<2.2,>=2.1'
    - torchsde
    - opencv-python
    - torchdiffeq
    - wandb